sudo: false
language: cpp

os:
- osx

before_install:
- system_profiler SPHardwareDataType
- #ls -l /usr/local
- #find -x -path /usr -and -not -path '/usr/sbin' -name '*matplotlib*'  -exec ls -l {} \;
- #find -x /usr -name '*FreeCAD*' -not -path '/usr/sbin/' -exec ls -l {} \;
- brew update
- brew tap homebrew/science
- brew tap sanelson/freecad
- brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl
- brew install --without-framework --without-soqt sanelson/freecad/coin
- brew install --HEAD pivy
- pip install --quiet --upgrade pip setuptools
- #pip install --quiet matplotlib==1.4.3
- git clone https://github.com/Heeks/libarea.git ./libarea
- pushd ./libarea && mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/ -DPYTHON_DIR=$(python-config --exec-prefix)/bin/ ../
- make -j2 install
- popd
- if [ -e /usr/local/lib/libgdal.1.dylib ]; then brew unlink gdal; fi
- brew list
- brew info freetype
- #find -x /usr/lib -name '*freetype*' -exec ls -l {} \;

install:
- mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON -DFREETYPE_INCLUDE_DIR_freetype2=/usr/local/include/freetype2 -DCMAKE_BUILD_TYPE=Debug ../

script:
- #make -j2
- #bin/FreeCAD --run-test 0
- #bin/FreeCAD --log-file /tmp/FreeCAD.log &
- #sleep 10 && pkill FreeCAD
- #cat /tmp/FreeCAD.log
- #grep --file=../.log_errors /tmp/FreeCAD.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from build directory" || ( echo "Error from .log_errors found!" && false )
- sudo make -j2 install
- #/usr/local/FreeCAD.app/Contents/bin/FreeCAD --run-test 0
- #/usr/local/FreeCAD.app/Contents/bin/FreeCAD --log-file /tmp/FreeCAD_installed.log &
- #sleep 10 && pkill FreeCAD
- #cat /tmp/FreeCAD_installed.log
- #grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )

after_success:
- #find -x /usr -name 'Version.h' -exec cat {} \;
- export VSN=$(sed -E -n -e 's/(^#define FCRevision.*")([0-9]+)(.*Git.*$)/\2/p' ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h)-${TRAVIS_COMMIT:0:7}
- echo "Version = $VSN"
- export DEPLOY_ARCHIVE_NAME="FreeCAD_osx-${VSN}"
- ls -l /usr/local
- cd /usr/local && zip -q -r -X "${DEPLOY_ARCHIVE_NAME}.zip" FreeCAD.app -x FreeCAD.app/Contents/doc*
- ls -l /usr/local
- travis_retry curl --ftp-create-dirs -T ${DEPLOY_ARCHIVE_NAME}.zip -u ${FTP_USER}:${FTP_PASSWORD} ftp://${FTP_HOST}/${DEPLOY_ARCHIVE_NAME}.zip

deploy:
  provider: releases
  api_key:
    secure: DlnEwU6+O3vt2mAy0lvD5qhsw8p4yo3eIpH6xRqU5goKfUYXWLU7h/+C2MQsyof6mD2ZPrHH7PHgwBdif2lcIy3aRDc+F3ocSQBEQcjm+FEq/vLNb3QR5q+k/sLl0u+Va/TamU/KLlTIRpDelWL/9Ik5NaGR7nvxkFw6a8fAkS1cTbqwMpPCtuju+Uv6Ahs7peYRkAVbalJ82oP3651pinHJKgljhY76+35IJS2H5mr2biFTGFBX/lnvfSxbhM5kKvJWBuYX3VWEuXcNE3o86itswruLEV4krJcyU6TUr8KA+uPBVgkf0TFQyPW1t7c6UH4KLSmqP8AmcfO+qzj2Ex+FqFNCubLyXHkED4Yss2OnxLh2J6sxzEyHhE5UXHHUAvOgeYATtMcQ9K6nHdUtIBoga14HMURJkcdQMel0Wc6t18MZrJnnzykzmqOVNpg1f1AcPcE0ZkLzaFA34Kq04DoHEB2LOscIAuC+sbXPHkb6cdycz5qP80a1VNMpek5QZgmjHhp1Vi2PdlMEl+ezp9e/QLfHjo4Yge98EtkiaiXH1DKARkJlKFXQL9OKKovnQtNRcvJhCUGymgTXXaBomyk6U0DWak8AONj7DYwtnVfFlBZ10TgCd+0oNuLtni9k64xc13aI224i0Y3BDrgn62ycAvha8Ecmn5nWbkzSva8=
  file: "/usr/local/${DEPLOY_ARCHIVE_NAME}.zip"
  on:
    repo: bblacey/FreeCAD-MacOS-CI
    all_branches: true
    tags: true

notifications:
  pushover:
    api_key:
      secure: SEwbkIvChyaUwuXhtXPIMISAlWPSHx5PQH/YkHZn83fnaOYCJRfkare6NIeBGm5ruxZmETeS1D9rHqohSBVXeGqgCp5VfGacZ0/d/spnq2gb+MqT2/fzbjB/RHpZWuxL4P7j7kTdqOq/jO35aQa+df512cwrmkA4ZWLnFR47EgvWdBjP73DMSes5cIR3rr6ftASYyVfI1IlUZsBgZFJf9KZ+Mb/VRCo6CvO5S08ZEdww0i5fzNx/H0DkxMul2TDH9mc+RFD8n+8Q/ihJhP84b8+XGwjQJwvNWqIFpNya3gaDzjidI8w3R8uekOBlRgK5IBpgyXQfY3BCmvyfurIeKoqGxSPUxz3jXdGfObCfCQ6H6oDFuBAfozx5aBlYSiaUdiZ7Y6RMUK3PyVBAiHNsjknRhWBIMvebp8nTQPvCRRFXwK2LRpwuVB9gh9fq9YATFjphSu9seX54U0mpX3DnfAAHb1BXnFm3IlU3V1KIAI53m9WGO4FSWbwafcrGTg4zIIH8RI8X7b0Z3Ay6DpYcwj8zUnajCJAgfil7dSMC+4fL/+b7KacqTv8YAHZkNTktjvh9pEzS+K9JkuLVMklt4J8L0hl68gy0/e1pfi6EBAeQHis6aG5XW7tF9dTI0kF/yrSfTFIHc0L+BRx2xQ7vbgWnyHsN+TUTXqgjRriXKrM=
    users:
      secure: hDFxK5UrjzSQoMoayjfFZU5q2ddJAymS2jIQWQedMGYlTnUilRtpZl4UuOHd59ZnDtcNVP86olUKgYJc/PaIyZZpOafyDyttkNmzV/09EapdSwM4AaTU04QxMNhle7nqCqigza0maDiKFM+LyZMXvsa91A85U2Y93kMtzh2m0yetHau7a97aKNK/B94uRKuNxdvZID+i/BA13OqJGz/JKiYt6S3yEowTSEzbx9plKxbLb3qaI5i3T7mx2CedbQPopMy5wILxCv1fhqyC2+JvH0scuTM54Y1AOJZr6JZo3nNys8fWFqoWUtBdBZcv+qRWljJBKXDGK0iYrh09CG4TXxv61MOqnNm2oQRPwJ3KeVs4dsMeyZI7V94gV5fnUOxgEu7a6ImzAiuQITaG6AWl4h1nURHGfKNJeJ+wgjkuCZLUEZV3vPnEpH87jpyXfzM7vVh/NdRN+/pPN9dKb8Q9QsizsgK1NW/o63g07RnOVMxxNKCe16foad6n7uf6vuIIufJrC2U+FtWklWqq7VJCp2znrBiUf5EEoiziIbcHn4B2kSmOEIn8YLqrf1vytUdYy0BY8IdO7qZ15nhQelDwHDAd3fK7J066GeXevSgJwZ20uYgYTdD2tOp8UuqjW3Le715hy/w96OWUUfUOw+Qyj6+q2ig78DbYcKlL4sKKHq0=
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"

env:
  global:
  - secure: RAAE+6cnvVI1ZDX1it8K+VuwcC6Lt0SKy9XWCpyXcRZxoFe8QkJSPBJfJGSnri0tAc/vmxOG0WmahibxpT4RFyu4cEMyaXr/P22sRCrW/CYvr+drZF/QHNLx9XndUy4PnWBih6ZJXlEUiszMlM9/pCIt8Ig+cFDSCclQgMCO2rqtUn03m9/EHTX2a1ct2eOPNlFgTPc/pJ1Vld7VBEUCz+de+U3yEyFAQtZO0qmuSobqkyDmEDXXff5JTsMcxl+Hm8RMYVKuUr7iatQgY7ywOMCpw/4qaSQOcNi86jEeewQiqmqneg1II69/Ory5NwxsS7hbHbYm2KADM5JHIoBaNvg9W5SZYz0rzbdm1rcktuEfBaqr/6r4m8i54dIzyJvn66b4IxE5ELzCZLxg5Wb+kM29H7KYeytEoOR+Bge0Vvg6E1QP6huQ9zPKR0+oaepFL6Vp31fRZc1mwMTKXMPCggHrR0e4nsi/oJEkqDGvAna6QqekkgNQtAT0+9TP3s7IcQvEu0V2iGhR4qG149mFYMI3dh7Dfd990lY1acJTdjS4/nSjGtaRluDlWXXQw9+W5CBSA/DTI1RWpytUQ6M0wSymbJokr0aR9HACmxjh8LJZK/ZSjYU+7i71oGMjiCve7gMCSI7UQ1KEIbm2UXhhNyKrMVGc2iqRtOgUt7JT1ac=
  - secure: I+JBrmnlD+/BchmPXvkL+cDzjRmlziJNGniFEHmHZ7GPkjpZ11muQ8/YH9BZ4sFmxOq5EmlMcsaE5Z9AcA4V0ZXpfum4MqISF+oV15Ai4ijiZN4PxvHt9JOWTDtAYJ1XytbH/8vIzQrtqwJMJdLsFOqI3sP0MX2xAKbctsGirujKr8Fr7VVBapBnq3c36uekGtV7ynE4w9OAWNGdLSMF2dre4lSld1qWZ3dd3tllhc3sDCxOr9PFdeBWU5apUoYXTVNwe8TBGscy3joO+h1dEwIfNt4c/IPdpEk3EZfTdGGCFUAeopH/o/9A2/+nRcd8ul0YZwpvEEBoOnt4/TjpAbIRseyXdL9k0MYudFtqWRyvRK3+Xn20+FH781vwY8QrWhdv5nEWBK3vlDgA8J85tRYTrVkWYQ9BY1MFYXhjxPnRJCQpu+HHVVYAI3DMWeE5LxWuvGOkqx6hICUHJHFCcVp1z99UqfdTqvb2QiVmtBZ2vRz6WQlKGVy2mo2Qb0Ebam1lq+pkF+S4su9ZCrElNlohwA/n0qn8zCIWn9FVgu8kCo1n8vLl25v8DFMd02WX1Qt6UfzM8mznb34Uj3ttsjjJlOiP9N2tjwGvLQPCDZ6rxeQfk6rjv7c8JcTFmd/Svlpiw+joRkFZd+letBHxD6d7QGB5jfAh1B04Ifo1eOw=
  - secure: sc/kwCm5XT1apHN6XzqRSsPf3/npKZjV6YSGmpJKMHJpvZFFM3is9e+WDH08+jA18Dqhtg5QfAOuh/2BD7qL+SPCqrAamm4qU8pgHZIfxjIP8NkLhdsBgEQwaZic991ZySnEPt6t+aAHboAxefKbjtab9vuYNE1al9tJ0QPepKFtYjISgTc9yhXySe16mrm1BKQhp9OhYExeQVTR74yRrTkejA+2RJVve/HEFYTQw01aEwIGZiBpQfXxnXJ3p6663cgwVzCffct0nzXuxxCMW9EB+VY+77fAqfAKTSWxu1z4NbHQ4t8Fhm9nIy/rMFxPrLnKn79N8KtIIK/ELW+uaIEO+4R/ScjfsR+1758isque7siEALtlmq7I2W9ggVQVduXJkoRjR9tkAO5DdHFoWdJ6wAwavkGtAmgGVWk/tkZhprgwKF8UC9ImIfyJGVKyhwVzu+u6D8XUI/TUHov3ZoAy9wCITCZVc7A9idPfq10nxu/b+P3W4cnLOmK3S7t3zqO6nP8OIVVooQH/Er35llkeYT+Noxgfr6B4KP/y2CIk+Pn23OUoeglWByQCRokyA45q5Omsf8cXddVbfuOfArmE7mp1cL1a4tEoaD8RzNspd7VuDenntDKpR6+4SmIstmcU/XdOrX8OkB0yYTjWkLA6iBqklFqMrCSPB7ZZUb4=
