env:
  global:
  - GH_RELEASE_NAME="deploy-test"

language: cpp

os:
- osx

git:
  depth: 800

before_install:
- brew update
- brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl homebrew/python/matplotlib
- brew install --without-framework --without-soqt sanelson/freecad/coin
- brew install --HEAD pivy
- if [ -e /usr/local/lib/libgdal.1.dylib ]; then brew unlink gdal; fi
# Installed 3DConnexion frameworks
- curl -o /tmp/3dFW.dmg -L 'http://www.3dconnexion.com/index.php?eID=sdl&ext=tx_iccsoftware&oid=a273bdbc-c289-e10d-816b-567043331c9e&filename=3DxWareMac_v10-2-5_r2142.dmg' && hdiutil mount /tmp/3dFW.dmg
- sudo installer -package /Volumes/3Dconnexion\ Software/Install\ 3Dconnexion\ software.pkg -target /

install:
- mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON -DFREECAD_USE_3DCONNEXION=ON -DCMAKE_BUILD_TYPE=Debug ../

script:
- sudo make -j2 install
- /usr/local/FreeCAD.app/Contents/bin/FreeCAD --run-test 0
- /usr/local/FreeCAD.app/Contents/bin/FreeCAD --log-file /tmp/FreeCAD_installed.log &
- sleep 10 && pkill FreeCAD
- cat /tmp/FreeCAD_installed.log
- grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
- #pushd /usr/local/FreeCAD.app/Contents
- #PYTHONPATH=$(pwd)/lib/ python -c "import sys, unittest, FreeCAD, Plot; Plot.figure("TrigonometricTest");"
- #popd

after_success:
- export VSN=$(python ${TRAVIS_BUILD_DIR}/src/Tools/ArchiveNameFromVersionHeader.py ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h --git-SHA=$(git ls-remote origin master))
- export DEPLOYMENT_ARCHIVE=${VSN}.dmg
- echo ${DEPLOYMENT_ARCHIVE}
- node --version
- npm install -g appdmg
- pip install dmgbuild
- dmgbuild -s ${TRAVIS_BUILD_DIR}/src/Tools/DMGSettings.py "${VSN}" ${DEPLOYMENT_ARCHIVE}
- #travis_retry curl --ftp-create-dirs -T ${DEPLOYMENT_ARCHIVE} -u ${FTP_USER}:${FTP_PASSWORD} ftp://${FTP_HOST}/${DEPLOYMENT_ARCHIVE}
- brew install jq
- export UPLOAD_URL=$(curl -s -u "${GH_TOKEN}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases" | jq ".[] | select(.name==\"${GH_RELEASE_NAME}\").upload_url" | cut -d '{' -f 1 | cut -c 2- )
- echo "${UPLOAD_URL}"
- if [ -n "${UPLOAD_URL}" ]; then curl -X POST -s -u "${GH_TOKEN}" -H "Content-Type:application/x-apple-diskimage" --data-binary "@${DEPLOYMENT_ARCHIVE}" "${UPLOAD_URL}?name=${DEPLOYMENT_ARCHIVE}"; fi

after_script:
- if [ ${TRAVIS_TEST_RESULT} == 0 ]; then export MSG="SUCCEEDED"; else export MSG="FAILED"; fi
- curl -s --form-string "token=${PO_APP}" --form-string "user=${PO_USER}" --form-string "html=1" --form-string 
  "message=FreeCAD OS X build ${VSN} <b>${MSG}</b> (${TAVIS_REPO_SLUG}/${TRAVIS_BRANCH}#${TRAVIS_BUILD_NUMBER})</b><br> 
  <a href=\"https://api.travis-ci.org/jobs/${TRAVIS_JOB_ID}/log.txt?deansi=true\">Build ${TRAVIS_BUILD_NUMBER} Log</a><br>
  <a href=\"https://github.com/bblacey/FreeCAD-MacOS-CI/releases/tag/${TRAVIS_COMMIT}\">Download build ${VSN} from GitHub</a>"
  https://api.pushover.net/1/messages.json
