sudo: false
language: cpp
os:
- osx

before_install:
- system_profiler SPHardwareDataType
- brew update
- brew tap homebrew/science
- brew tap sanelson/freecad
- brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl
- brew install --without-framework --without-soqt sanelson/freecad/coin
- brew install --HEAD pivy
- pip install --upgrade pip setuptools
- pip install matplotlib
- git clone https://github.com/Heeks/libarea.git ./libarea
- pushd ./libarea && mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/ -DPYTHON_DIR=$(python-config --exec-prefix)/bin/ ../
- make -j2 install
- popd
- brew list
- ls -l /usr/local/lib
- if [ -e /usr/local/lib/libgdal.1.dylib ]; then brew unlink gdal; fi
- ls -l /usr/local/lib/

install:
- mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON ../

script:
- make -j2
- bin/FreeCAD --run-test 0
- bin/FreeCAD --log-file /tmp/FreeCAD.log &
- sleep 10 && pkill FreeCAD
- cat /tmp/FreeCAD.log
- grep --file=../.log_errors /tmp/FreeCAD.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from build directory" || ( echo "Error from .log_errors found!" && false )
- sudo make install/fast
- /usr/local/FreeCAD.app/Contents/bin/FreeCAD --run-test 0
- /usr/local/FreeCAD.app/Contents/bin/FreeCAD --log-file /tmp/FreeCAD_installed.log &
- sleep 10 && pkill FreeCAD
- cat /tmp/FreeCAD_installed.log
- grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )

before_deploy:
- export VSN=$(sed -E -n -e 's/(^#define FCRevision.*")([0-9]+)(.*Git.*$)/\2/p' ${TRAVIS_BUILD_DIR}/build/src/Build/Version.h)
- export DEPLOY_ARCHIVE_NAME="FreeCAD_osx-${VSN}"
- cd /usr/local && zip -r -X "${DEPLOY_ARCHIVE_NAME}.zip" FreeCAD.app -x FreeCAD.app/Contents/doc*

deploy:
  provider: releases
  api_key:
    secure: 1g1niXRAyDjYGMMwcWVDTjMjV6z3ErYkNx1PzR7Clq2ygDO0smpwAJ0QUxtTwn2BvnhdCqRNcGIHUugHCvB5XxgbVQZCTZCbbIt3hTLK7+FMXb5QT2ROokPrLuzPgoHSsPNqR++LRCarjk6xtzGaGTLDtv58BaiantMjQ9dGzzifFEgHVCGSMkSfRhdkc1hwQsDlvSbZfKl8vt0GLSGuMcCcBovpUHJ59Aqv0Kg7QhhCzqcUSnb//1IvF9wOcRB0VjuRQvoTPwMe2Qf2XtFxqjern0DhZR0DlvzjZcTh6joWrHJraouuUM6psV6cl0b3KGQCCWGBxUaMbdxurRLaMm2T6v0nzV2veeAcdocCJ6Ii3p5b3SXuySyUK+I4OJ0rU315d5yzveIy1kTQMJtaYRABcKaiQ+bxcFcnBP+k11S00mTmPsZT8fu6iGi/vCHAOn72xcD+URPhW2X4wnVQfIXACmKgRy1LrSajv2trAZHFkEnOFqiK2rSZxYAtiHcRODFNhYiWBlLdc0E1b3Dc7JZ56JWKx4wtU8Xp9YtAeTZ2Gj6aD/rkIN/+PpGaGqhgCEn7A8QHSgz+xkSP+Nfw1+TucPhGoEsV4JICAjS9b7h0SyOVKTqc2R8ip3Crya5u1lUREPdlPDdnrdMg7cEhvVNoIcXL3M0TV/xXaJZvOIE=
  file: /usr/local/${DEPLOY_ARCHIVE_NAME}.zip
  skip_cleanup: true
  on:
    repo: bblacey/FreeCAD-MacOS-CI
    all_branches: true
    tags: true

notifications:
  pushover:
    api_key:
      secure: SEwbkIvChyaUwuXhtXPIMISAlWPSHx5PQH/YkHZn83fnaOYCJRfkare6NIeBGm5ruxZmETeS1D9rHqohSBVXeGqgCp5VfGacZ0/d/spnq2gb+MqT2/fzbjB/RHpZWuxL4P7j7kTdqOq/jO35aQa+df512cwrmkA4ZWLnFR47EgvWdBjP73DMSes5cIR3rr6ftASYyVfI1IlUZsBgZFJf9KZ+Mb/VRCo6CvO5S08ZEdww0i5fzNx/H0DkxMul2TDH9mc+RFD8n+8Q/ihJhP84b8+XGwjQJwvNWqIFpNya3gaDzjidI8w3R8uekOBlRgK5IBpgyXQfY3BCmvyfurIeKoqGxSPUxz3jXdGfObCfCQ6H6oDFuBAfozx5aBlYSiaUdiZ7Y6RMUK3PyVBAiHNsjknRhWBIMvebp8nTQPvCRRFXwK2LRpwuVB9gh9fq9YATFjphSu9seX54U0mpX3DnfAAHb1BXnFm3IlU3V1KIAI53m9WGO4FSWbwafcrGTg4zIIH8RI8X7b0Z3Ay6DpYcwj8zUnajCJAgfil7dSMC+4fL/+b7KacqTv8YAHZkNTktjvh9pEzS+K9JkuLVMklt4J8L0hl68gy0/e1pfi6EBAeQHis6aG5XW7tF9dTI0kF/yrSfTFIHc0L+BRx2xQ7vbgWnyHsN+TUTXqgjRriXKrM=
    users:
      secure: hDFxK5UrjzSQoMoayjfFZU5q2ddJAymS2jIQWQedMGYlTnUilRtpZl4UuOHd59ZnDtcNVP86olUKgYJc/PaIyZZpOafyDyttkNmzV/09EapdSwM4AaTU04QxMNhle7nqCqigza0maDiKFM+LyZMXvsa91A85U2Y93kMtzh2m0yetHau7a97aKNK/B94uRKuNxdvZID+i/BA13OqJGz/JKiYt6S3yEowTSEzbx9plKxbLb3qaI5i3T7mx2CedbQPopMy5wILxCv1fhqyC2+JvH0scuTM54Y1AOJZr6JZo3nNys8fWFqoWUtBdBZcv+qRWljJBKXDGK0iYrh09CG4TXxv61MOqnNm2oQRPwJ3KeVs4dsMeyZI7V94gV5fnUOxgEu7a6ImzAiuQITaG6AWl4h1nURHGfKNJeJ+wgjkuCZLUEZV3vPnEpH87jpyXfzM7vVh/NdRN+/pPN9dKb8Q9QsizsgK1NW/o63g07RnOVMxxNKCe16foad6n7uf6vuIIufJrC2U+FtWklWqq7VJCp2znrBiUf5EEoiziIbcHn4B2kSmOEIn8YLqrf1vytUdYy0BY8IdO7qZ15nhQelDwHDAd3fK7J066GeXevSgJwZ20uYgYTdD2tOp8UuqjW3Le715hy/w96OWUUfUOw+Qyj6+q2ig78DbYcKlL4sKKHq0=
    template:  "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"

